# Generated by Django 3.0.7 on 2020-07-19 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mag_title', models.CharField(max_length=50)),
                ('mag_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('mag_pdf', models.FileField(blank=True, null=True, upload_to='')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archives.Year')),
            ],
        ),
    ]
