# Generated by Django 3.0.7 on 2020-07-17 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ananda_vani', models.TextField()),
                ('slider1_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('slider1_title', models.CharField(max_length=250)),
                ('slider2_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('slider2_title', models.CharField(max_length=250)),
                ('slider3_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('slider3_title', models.CharField(max_length=250)),
                ('slider4_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('slider4_title', models.CharField(max_length=250)),
                ('slider5_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('slider5_title', models.CharField(max_length=250)),
                ('slider6_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('slider6_title', models.CharField(max_length=250)),
                ('recent1_title', models.CharField(max_length=250)),
                ('recent1_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('recent1_pdf', models.FileField(blank=True, null=True, upload_to='')),
                ('recent2_title', models.CharField(max_length=250)),
                ('recent2_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('recent2_pdf', models.FileField(blank=True, null=True, upload_to='')),
                ('recent3_title', models.CharField(max_length=250)),
                ('recent3_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('recent3_pdf', models.FileField(blank=True, null=True, upload_to='')),
                ('act1_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('act1_title', models.CharField(max_length=250)),
                ('act1_desc', models.TextField()),
                ('act2_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('act2_title', models.CharField(max_length=250)),
                ('act2_desc', models.TextField()),
                ('act3_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('act3_title', models.CharField(max_length=250)),
                ('act3_desc', models.TextField()),
                ('act4_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('act4_title', models.CharField(max_length=250)),
                ('act4_desc', models.TextField()),
                ('act5_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('act5_title', models.CharField(max_length=250)),
                ('act5_desc', models.TextField()),
                ('act6_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('act6_title', models.CharField(max_length=250)),
                ('act6_desc', models.TextField()),
                ('current_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('current_pdf', models.FileField(blank=True, null=True, upload_to='')),
                ('editorial_title', models.CharField(max_length=50)),
                ('editorial_intro', models.TextField(blank=True, null=True)),
                ('editorial_desc', models.TextField()),
                ('coverstory_title', models.CharField(max_length=50)),
                ('coverstory_intro', models.TextField(blank=True, null=True)),
                ('coverstory_desc', models.TextField()),
                ('ad_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('partner1_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('partner1_title', models.CharField(max_length=20)),
                ('partner2_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('partner2_title', models.CharField(max_length=20)),
                ('partner3_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('partner3_title', models.CharField(max_length=20)),
                ('editor', models.CharField(max_length=50)),
                ('editorial_board', models.CharField(max_length=70)),
                ('general_manager', models.CharField(max_length=50)),
                ('business_director', models.CharField(max_length=50)),
                ('circular_manager', models.CharField(max_length=50)),
                ('correspondents', models.CharField(max_length=50)),
            ],
        ),
    ]
