# Generated by Django 3.0.7 on 2020-07-17 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='edit',
            name='partner4_img',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='edit',
            name='partner4_title',
            field=models.CharField(default='', max_length=20),
        ),
    ]
