# Generated by Django 3.0.7 on 2020-07-17 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edits', '0002_auto_20200717_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edit',
            name='editorial_board',
            field=models.CharField(max_length=100),
        ),
    ]
