# Generated by Django 3.0.7 on 2020-07-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edits', '0005_edit_coverstory_writer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=70)),
                ('phone', models.CharField(max_length=70)),
                ('message', models.TextField()),
            ],
        ),
    ]
