# Generated by Django 3.0.7 on 2020-07-26 07:07

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edits', '0007_auto_20200725_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edit',
            name='editorial_desc',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
