# Generated by Django 3.0.7 on 2020-08-05 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0003_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_icon',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
    ]
