# Generated by Django 3.0.7 on 2020-08-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0004_item_item_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_icon',
        ),
        migrations.AddField(
            model_name='download',
            name='item_icon',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
    ]
